language: cpp

os:
  - linux
  - osx

osx_image: xcode9.2

env:
  global:
    - SHELL_SESSION_HISTORY=0
  matrix:
    - BUILD=Release
    - BUILD=Debug

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - python-numpy
      - python-matplotlib
      - python3-numpy
      - python3-matplotlib

compiler:
    - gcc
    - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable --auto-dotfiles; fi

before_script:
    - set -e
    - cmake --version
    - which python
    - python --version
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python@2; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $PWD/fakepy3 && echo '/usr/local/bin/python "$@"' > $PWD/fakepy3/python3 && chmod +x $PWD/fakepy3/python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/python@2/libexec/bin:/usr/local/bin:$PWD/fakepy3:$PATH"; fi
    - echo $PATH
    - echo $PWD/fakepy3
    - ls -l $PWD/fakepy3 || echo notfound
    - which python
    - python --version
    - which python2
    - python2 --version
    - which python3 || echo "python3 not found"
    - python3 --version
    - python2 -c 'import numpy' 2>/dev/null || python2 -mpip install numpy
    - python3 -c 'import numpy' 2>/dev/null || python3 -mpip install numpy
    - python2 -c 'import numpy; print numpy.__version__'
    - python3 -c 'import numpy; print(numpy.__version__)'
    - mkdir build installdir rundir
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../installdir/
    - set +e

script:
    - set -e
    - make VERBOSE=1 install
    - cd ../rundir
    - find ../installdir
    - ../installdir/bin/ncrystal_example_c
    - ../installdir/bin/ncrystal_example_cpp
    - mkdir fakebin && touch fakebin/python && chmod +x fakebin/python
    - export PATH="$PWD/fakebin:$PATH"
    - echo 'python2 "$@"' > fakebin/python && python --version
    - ../installdir/bin/ncrystal_inspectfile --help
    - ../installdir/bin/ncrystal_inspectfile --test
    - ../installdir/bin/ncrystal_inspectfile --dump Al_sg225.ncmat
    - python -c 'import matplotlib' 2>/dev/null || python -mpip install matplotlib
    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
    - . ../installdir/setup.sh
    - ../installdir/bin/ncrystal_example_py
    - python -c 'import NCrystal; NCrystal.test()'
    - echo 'python3 "$@"' > fakebin/python && python --version
    - ../installdir/bin/ncrystal_inspectfile --help
    - ../installdir/bin/ncrystal_inspectfile --test
    - ../installdir/bin/ncrystal_inspectfile --dump Al_sg225.ncmat
    - python -c 'import matplotlib' 2>/dev/null || python -mpip install matplotlib
    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
    - . ../installdir/setup.sh
    - ../installdir/bin/ncrystal_example_py
    - python -c 'import NCrystal; NCrystal.test()'
    - set +e

notifications:
  email:
    recipients:
      - ncrystal-developers@cern.ch
    on_success: change
    on_failure: always
