language: cpp

os:
  - linux
  - osx

env:
    - BUILD='Release'
    - BUILD='Debug'

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
      - python-numpy
      - python-matplotlib

compiler:
    - gcc
    - clang

#Trying to test g4 via homebrew on osx. But fails when building libG4NCrystal. To be investigated.
#before_install:
#    - set -e
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then brew update                         ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then brew install homebrew/science/geant4; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --version; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --libs; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --cflags; fi
#    - set +e

before_script:
    - set -e
    - cmake --version
    - python --version
    - python -c 'import numpy' 2>/dev/null || pip install numpy
    - python -c 'import numpy; print numpy.__version__'
    - mkdir build installdir rundir
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../installdir/
    - set +e

script:
    - set -e
    - make VERBOSE=1 install
    - cd ../rundir
    - find ../installdir
    - ../installdir/bin/ncrystal_example_c
    - ../installdir/bin/ncrystal_example_cpp
    - ../installdir/bin/ncrystal_inspectfile --help
    - ../installdir/bin/ncrystal_inspectfile --test
    - ../installdir/bin/ncrystal_inspectfile --dump Al_sg225.ncmat
    - python -c 'import matplotlib' 2>/dev/null || pip install matplotlib
    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
    - . ../installdir/setup.sh
    - ../installdir/bin/ncrystal_example_py
    - python -c 'import NCrystal; NCrystal.test()'
    - set +e

notifications:
  email:
    recipients:
      - ncrystal-developers@cern.ch
      - tkess@doki.dk
    on_success: change
    on_failure: always
