language: cpp

os:
  - linux
  - osx

env:
    - BUILD='Release'
    - BUILD='Debug'

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - python-numpy
      - python-matplotlib

compiler:
    - gcc
    - clang

before_script:
    - set -e
    - cmake --version
    - python --version
    - python -c 'import numpy' 2>/dev/null || pip install numpy
    - python -c 'import numpy; print numpy.__version__'
    - mkdir build installdir rundir
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../installdir/
    - set +e

script:
    - set -e
    - make VERBOSE=1 install
    - cd ../rundir
    - find ../installdir
    - ../installdir/bin/ncrystal_example_c
    - ../installdir/bin/ncrystal_example_cpp
    - ../installdir/bin/ncrystal_inspectfile --help
    - ../installdir/bin/ncrystal_inspectfile --test
    - ../installdir/bin/ncrystal_inspectfile --dump Al_sg225.ncmat
    - python -c 'import matplotlib' 2>/dev/null || pip install matplotlib
    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
    - . ../installdir/setup.sh
    - ../installdir/bin/ncrystal_example_py
    - python -c 'import NCrystal; NCrystal.test()'
    - set +e

notifications:
  email:
    recipients:
      - ncrystal-developers@cern.ch
    on_success: change
    on_failure: always
