name: CMake

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: src

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build

    - name: Check python
      run: which python3 && python3 --version

    - name: Look around
      run: ls -l ${{github.workspace}}/install && find ${{github.workspace}}/install && ls -l ${{github.workspace}}/install/bin/ncrystal_inspectfile

    - name: Tests without setup.sh
      run: |
           ${{github.workspace}}/install/bin/ncrystal_inspectfile --test
           ${{github.workspace}}/install/bin/ncrystal-config --help
           ${{github.workspace}}/install/bin/ncrystal_example_c
           ${{github.workspace}}/install/bin/ncrystal_example_cpp
           ${{github.workspace}}/install/bin/ncrystal_inspectfile --help
           ${{github.workspace}}/install/bin/ncrystal_inspectfile --test
           ${{github.workspace}}/install/bin/ncrystal_inspectfile --dump 'Al_sg225.ncmat;dcutoff=1.5'
           ${{github.workspace}}/install/bin/ncrystal_inspectfile --dump 'Al_sg225.nxs;dcutoff=1.5'
    - name: Tests with setup.sh
      run: |
           . ${{github.workspace}}/install/setup.sh
           ncrystal_inspectfile --test
           ncrystal-config --help
#
#    - python3 -c 'import matplotlib' 2>/dev/null || python3 -mpip install matplotlib
#    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
#    - . ../installdir/setup.sh
#    - ../installdir/bin/ncrystal_example_py
#    - python3 -c 'import NCrystal; NCrystal.test()'
#    - ../installdir/bin/ncrystal_inspectfile --help
#    - ../installdir/bin/ncrystal_inspectfile --test
#    - ../installdir/bin/ncrystal_inspectfile --dump Al_sg225.ncmat
#    - ../installdir/bin/ncrystal_inspectfile --pdf Al_sg225.ncmat
#    - . ../installdir/setup.sh
#    - ../installdir/bin/ncrystal_example_py
#    - python3 -c 'import NCrystal; NCrystal.test()'
##do not run vdos2ncmat/endf2ncmat with 3.5, (uses f-strings from py3.6):
#    - python3 --version
#    - python3 -c "import sys;sys.exit(1 if sys.version_info[0:2]>=(3,6) else 0)" || ../installdir/bin/ncrystal_vdos2ncmat --help
##requires pyne!    - python3 -c "import sys;sys.exit(1 if sys.version_info[0:2]>=(3,6) else 0)" || ../installdir/bin/ncrystal_endf2ncmat --help
#    - ../installdir/bin/ncrystal_ncmat2cpp --help
#    - ../installdir/bin/ncrystal_ncmat2cpp $(../installdir/bin/ncrystal-config --show=datadir)/Al_sg225.ncmat -o test.cpp
#    - cat test.cpp
#    - ../installdir/bin/ncrystal_verifyatompos --help
#    - ../installdir/bin/ncrystal_onlinedb2ncmat --help
#    - python3 -c 'import ase' 2>/dev/null || python3 -mpip install ase
#    - ../installdir/bin/ncrystal_verifyatompos Al2O3_sg167_Corundum.ncmat
#    - python3 -c 'import pymatgen' 2>/dev/null || python3 -mpip install pymatgen
#    - ../installdir/bin/ncrystal_onlinedb2ncmat --codid=9008460
#    - cat autogen_Al_sg225_cod9008460.ncmat
#    - set +e
#


