name: Publish to PyPI
run-name: Publish to ${{inputs.TEST && 'Test' || ''}}PyPI

on:
  push:
    tags:
      - 'v[0-9].*' #pattern match TEST
  workflow_dispatch:
    inputs:
      TEST:
        type: boolean
        description: Upload to TestPyPI (instead of the PyPI)
        default: true
      BUILD_ONLY:
        type: boolean
        description: Run building distributions without attempting to upload them
        default: false
      SKIP_EXISTING:
        type: boolean
        description: Allow skipping upload if the same version of a specific distribution is already uploaded
        default: true

jobs:
  use-pypi_deploy-workflow:
    uses: MilanKlausz/ncrystal_actions/.github/workflows/pypi_deploy.yml@main
    with:
      REPOSITORY: ${{ github.repository }}
      BRANCH: ${{ github.ref_name }}
      DO_DEPLOY: ${{ !inputs.BUILD_ONLY }}
      ENVIRONMENT: ${{ inputs.TEST && 'testpypi' || 'pypi' }}
      SKIP_EXISTING: ${{ inputs.SKIP_EXISTING || true }}
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
