name: Publish to PyPI
run-name: Publish to ${{inputs.TEST && 'Test' || ''}}PyPI

on:
  push:
    tags:
      - 'v[0-9].*' #pattern match
  workflow_dispatch:
    inputs:
      REF:
        type: string
        description: The repo ref (tag/branch) to use (defaults to the branch to use the workflow from)
      TEST:
        type: boolean
        description: Upload to TestPyPI (instead of the PyPI)
        default: true
      BUILD_ONLY:
        type: boolean
        description: Build distributions without deploying
        default: false


jobs:
  use-pypi_deploy-workflow:
    uses: MilanKlausz/ncrystal_actions/.github/workflows/pypi_deploy.yml@main
    with:
      REPOSITORY: ${{ github.repository }}
      REF: ${{ inputs.REF || github.ref_name }}
      DO_DEPLOY: ${{ !inputs.BUILD_ONLY }}
      ENVIRONMENT: ${{ inputs.TEST && 'testpypi' || 'pypi' }}
      SKIP_EXISTING: ${{ inputs.SKIP_EXISTING || true }}
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
